development:
  secret_key_base: 3807360bf648606618133ea14b885472eb89d0842ed7e8cad708bc9dcf3292979f514740dc9e3525c447bc847be18df266a78855df5e7dd87e7a10778e3ae83e
  twilio_account_sid: <%= ENV["TWILIO_ACCOUNT_SID"] %>
  twilio_auth_token: <%= ENV["TWILIO_AUTH_TOKEN"] %>
  redis_url: redis://localhost:6379
  default_admin_password: qweqwe123

test:
  secret_key_base: 3807360bf648606618133ea14b885472eb89d0842ed7e8cad708bc9dcf3292979f514740dc9e3525c447bc847be18df266a78855df5e7dd87e7a10778e3ae83e
  twilio_account_sid: ACef7fcdc16556c875b12595427be0ed98
  twilio_auth_token: e2575d7b9895229ae11a3e100dd2b502
  redis_url: redis://localhost:6379
  default_admin_password: qweqwe123

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  twilio_account_sid: <%= ENV["TWILIO_ACCOUNT_SID"] %>
  twilio_auth_token: <%= ENV["TWILIO_AUTH_TOKEN"] %>
  redis_url: <%= ENV["REDIS_URL"] %>
  default_admin_password: <%= ENV["DEFAULT_ADMIN_PASSWORD"] %>
